export interface AuthenticKoottaymaMeta {
  number: string;
  nameEn: string;
  nameMl: string;
  patronSaint: string;
  feastDate: string;
  location: string;
  zone: string;
  totalHouses: number;
}

export const AUTHENTIC_KOOTTAYMAS: Record<string, AuthenticKoottaymaMeta> = {
  '1': {
    number: '1',
    nameEn: 'St. Augustine Koottayma',
    nameMl: 'വി. അഗസ്റ്റിൻ',
    patronSaint: 'St. Augustine',
    feastDate: 'August 28',
    location: 'പി.പി. റോഡ് ഭാഗം',
    zone: '1 - ബേത്‌ലഹേം',
    totalHouses: 35,
  },
  '2': {
    number: '2',
    nameEn: 'St. Andrew Koottayma',
    nameMl: 'വി. അന്ത്രയോസ്',
    patronSaint: 'St. Andrew',
    feastDate: 'November 30',
    location: 'അട്ടിക്കൽ ഭാഗം',
    zone: '1 - ബേത്‌ലഹേം',
    totalHouses: 24,
  },
  '3A': {
    number: '3A',
    nameEn: 'St. Sebastian Koottayma (Unit 3A)',
    nameMl: 'വി. സെബാസ്റ്റ്യൻ',
    patronSaint: 'St. Sebastian',
    feastDate: 'January 20',
    location: 'പ്രശാന്ത് നഗർ',
    zone: '1 - ബേത്‌ലഹേം',
    totalHouses: 18,
  },
  '3B': {
    number: '3B',
    nameEn: 'St. Stephen Koottayma (Unit 3B)',
    nameMl: 'വി. സ്റ്റീഫൻ',
    patronSaint: 'St. Stephen',
    feastDate: 'December 26',
    location: 'പി.പി. റോഡ്',
    zone: '1 - ബേത്‌ലഹേം',
    totalHouses: 17,
  },
  '4A': {
    number: '4A',
    nameEn: 'St. John the Baptist Koottayma (Unit 4A)',
    nameMl: 'വി. സ്നാപകയോഹന്നാൻ',
    patronSaint: 'St. John the Baptist',
    feastDate: 'June 24',
    location: 'പി.പി. റോഡ് 1st മൈൽ',
    zone: '2 - നസ്രത്ത്',
    totalHouses: 21,
  },
  '4B': {
    number: '4B',
    nameEn: 'St. John Paul II Koottayma (Unit 4B)',
    nameMl: 'വി. ജോൺ പോൾ',
    patronSaint: 'St. John Paul II',
    feastDate: 'October 22',
    location: 'പ്രശാന്ത് നഗർ',
    zone: '2 - നസ്രത്ത്',
    totalHouses: 27,
  },
  '5A': {
    number: '5A',
    nameEn: 'St. Ambrose Koottayma (Unit 5A)',
    nameMl: 'വി. അംബ്രോസ്',
    patronSaint: 'St. Ambrose',
    feastDate: 'December 7',
    location: 'പി.പി. റോഡ് 1st മൈൽ',
    zone: '2 - നസ്രത്ത്',
    totalHouses: 22,
  },
  '5B': {
    number: '5B',
    nameEn: 'St. John XXIII Koottayma (Unit 5B)',
    nameMl: 'വി. ജോൺ 23',
    patronSaint: 'St. John XXIII',
    feastDate: 'October 11',
    location: 'പി.പി. റോഡ് 1st മൈൽ',
    zone: '2 - നസ്രത്ത്',
    totalHouses: 21,
  },
  '6A': {
    number: '6A',
    nameEn: 'St. Agnes Koottayma (Unit 6A)',
    nameMl: 'വി. ആഗ്നസ്',
    patronSaint: 'St. Agnes',
    feastDate: 'January 21',
    location: 'തച്ചപ്പുഴ ഭാഗം',
    zone: '2 - നസ്രത്ത്',
    totalHouses: 39,
  },
  '6B': {
    number: '6B',
    nameEn: 'St. Rani Maria Koottayma (Unit 6B)',
    nameMl: 'വി. റാണിമരിയ',
    patronSaint: 'St. Rani Maria',
    feastDate: 'February 25',
    location: 'തച്ചപ്പുഴ ഭാഗം',
    zone: '2 - നസ്രത്ത്',
    totalHouses: 18,
  },
  '7A': {
    number: '7A',
    nameEn: 'St. Albert Koottayma (Unit 7A)',
    nameMl: 'വി. ആൽബർട്ട്',
    patronSaint: 'St. Albert the Great',
    feastDate: 'November 15',
    location: 'കൊപ്രാക്കളം',
    zone: '3 - ഗലീലി',
    totalHouses: 32,
  },
  '7B': {
    number: '7B',
    nameEn: 'Bl. Pier Giorgio Koottayma (Unit 7B)',
    nameMl: 'വി. പിയർ ജോർജിയോ',
    patronSaint: 'Bl. Pier Giorgio Frassati',
    feastDate: 'July 4',
    location: 'കൊപ്രാക്കളം',
    zone: '3 - ഗലീലി',
    totalHouses: 24,
  },
  '8': {
    number: '8',
    nameEn: 'St. Ignatius Loyola Koottayma',
    nameMl: 'വി. ഇഗ്നേഷ്യസ് ലയോള',
    patronSaint: 'St. Ignatius of Loyola',
    feastDate: 'July 31',
    location: 'കൊപ്രാക്കളം',
    zone: '3 - ഗലീലി',
    totalHouses: 29,
  },
  '9': {
    number: '9',
    nameEn: 'St. Martin de Porres Koottayma',
    nameMl: 'വി. മാർട്ടിൻ ഡി പോറസ്',
    patronSaint: 'St. Martin de Porres',
    feastDate: 'November 3',
    location: 'കൊപ്രാക്കളം',
    zone: '3 - ഗലീലി',
    totalHouses: 28,
  },
  '10': {
    number: '10',
    nameEn: 'Queen of the Holy Rosary Koottayma',
    nameMl: 'പരി. ജപമാല രാജ്ഞി',
    patronSaint: 'Our Lady of the Holy Rosary',
    feastDate: 'October 7',
    location: 'നരിയനാനി ഭാഗം',
    zone: '4 - ബഥാനിയ',
    totalHouses: 28,
  },
  '11': {
    number: '11',
    nameEn: 'Rosa Mystica Koottayma',
    nameMl: 'വി. റോസ മിസ്റ്റിക്ക',
    patronSaint: 'Rosa Mystica',
    feastDate: 'July 13',
    location: 'നരിയനാനി - മാന്തറ',
    zone: '4 - ബഥാനിയ',
    totalHouses: 28,
  },
  '12': {
    number: '12',
    nameEn: 'St. Chavara Kuriakose Koottayma',
    nameMl: 'വി. ചാവറ കുര്യാക്കോസ്',
    patronSaint: 'St. Kuriakose Elias Chavara',
    feastDate: 'January 3',
    location: 'മാന്തറ ഭാഗം',
    zone: '4 - ബഥാനിയ',
    totalHouses: 30,
  },
  '13': {
    number: '13',
    nameEn: 'St. Antony Koottayma (Unit 13)',
    nameMl: 'വി. അന്തോണീസ്',
    patronSaint: 'St. Antony of Padua',
    feastDate: 'June 13',
    location: 'മാന്തറ ഭാഗം',
    zone: '4 - ബഥാനിയ',
    totalHouses: 21,
  },
  '14': {
    number: '14',
    nameEn: 'St. Clare Koottayma',
    nameMl: 'വി. ക്ലാര',
    patronSaint: 'St. Clare of Assisi',
    feastDate: 'August 11',
    location: 'പാട്ടുപാറ ഭാഗം',
    zone: '5 - സീനായ്',
    totalHouses: 15,
  },
  '15': {
    number: '15',
    nameEn: 'St. Gabriel Koottayma',
    nameMl: 'വി. ഗബ്രിയേൽ',
    patronSaint: 'St. Gabriel the Archangel',
    feastDate: 'September 29',
    location: 'പട്ടുപാറ ഭാഗം',
    zone: '5 - സീനായ്',
    totalHouses: 19,
  },
  '16': {
    number: '16',
    nameEn: 'St. Jerome Koottayma',
    nameMl: 'വി. ജെറോം',
    patronSaint: 'St. Jerome',
    feastDate: 'September 30',
    location: 'പാട്ടുപാറ - മാന്തറ',
    zone: '5 - സീനായ്',
    totalHouses: 29,
  },
  '17': {
    number: '17',
    nameEn: 'St. John the Apostle Koottayma',
    nameMl: 'വി. യോഹന്നാൻ',
    patronSaint: 'St. John the Apostle',
    feastDate: 'December 27',
    location: 'മാന്തറ ഭാഗം',
    zone: '5 - സീനായ്',
    totalHouses: 22,
  },
  '18A': {
    number: '18A',
    nameEn: 'St. John Chrysostom Koottayma (Unit 18A)',
    nameMl: 'വി. ജോൺ ക്രിസോസ്റ്റം',
    patronSaint: 'St. John Chrysostom',
    feastDate: 'September 13',
    location: 'കോയിപ്പള്ളി ഭാഗം',
    zone: '6 - താബോർ',
    totalHouses: 15,
  },
  '18B': {
    number: '18B',
    nameEn: 'Bl. Carlo Acutis Koottayma (Unit 18B)',
    nameMl: 'വി. കാർലോ അക്യൂട്ടിസ്',
    patronSaint: 'Bl. Carlo Acutis',
    feastDate: 'October 12',
    location: 'കോയിപ്പള്ളി ഭാഗം',
    zone: '6 - താബോർ',
    totalHouses: 19,
  },
  '19': {
    number: '19',
    nameEn: 'Holy Family Koottayma (Unit 19)',
    nameMl: 'ഹോളി ഫാമിലി',
    patronSaint: 'The Holy Family',
    feastDate: 'December (Last Sunday)',
    location: 'ശാന്തിഗ്രാം',
    zone: '6 - താബോർ',
    totalHouses: 20,
  },
  '20': {
    number: '20',
    nameEn: 'St. Maximilian Kolbe Koottayma',
    nameMl: 'വി. മാക്സിമില്യൻ കോൾബെ',
    patronSaint: 'St. Maximilian Kolbe',
    feastDate: 'August 14',
    location: 'ശാന്തിഗ്രാം',
    zone: '6 - താബോർ',
    totalHouses: 27,
  },
  '21A': {
    number: '21A',
    nameEn: 'St. Don Bosco Koottayma (Unit 21A)',
    nameMl: 'വി. ഡോൺ ബോസ്കോ',
    patronSaint: 'St. John Bosco',
    feastDate: 'January 31',
    location: 'കോയിപ്പള്ളി ഭാഗം',
    zone: '6 - താബോർ',
    totalHouses: 11,
  },
  '21B': {
    number: '21B',
    nameEn: 'Mar Ephrem Koottayma (Unit 21B)',
    nameMl: 'മാർ അപ്രേം',
    patronSaint: 'Mar Ephrem',
    feastDate: 'June 9',
    location: 'കോയിപ്പള്ളി ഭാഗം',
    zone: '6 - താബോർ',
    totalHouses: 14,
  },
  '22': {
    number: '22',
    nameEn: 'St. Dominic Savio Koottayma',
    nameMl: 'വി. ഡൊമിനിക് സാവിയോ',
    patronSaint: 'St. Dominic Savio',
    feastDate: 'May 6',
    location: 'പി.എൻ.പി. റോഡ്',
    zone: '7 - ജോർദ്ദാൻ',
    totalHouses: 19,
  },
  '23': {
    number: '23',
    nameEn: 'St. Thomas Aquinas Koottayma',
    nameMl: 'വി. തോമസ് അക്വിനാസ്',
    patronSaint: 'St. Thomas Aquinas',
    feastDate: 'January 28',
    location: 'ആനക്കയം ഭാഗം',
    zone: '7 - ജോർദ്ദാൻ',
    totalHouses: 23,
  },
  '24': {
    number: '24',
    nameEn: 'St. Thomas More Koottayma',
    nameMl: 'വി. തോമസ് മൂർ',
    patronSaint: 'St. Thomas More',
    feastDate: 'June 22',
    location: 'ആനക്കയം ഭാഗം',
    zone: '7 - ജോർദ്ദാൻ',
    totalHouses: 22,
  },
  '25A': {
    number: '25A',
    nameEn: 'St. Francis of Assisi Koottayma (Unit 25A)',
    nameMl: 'വി. ഫ്രാൻസിസ് അസീസി',
    patronSaint: 'St. Francis of Assisi',
    feastDate: 'October 4',
    location: 'പത്താശ്ശേരി',
    zone: '7 - ജോർദ്ദാൻ',
    totalHouses: 30,
  },
  '25B': {
    number: '25B',
    nameEn: 'Bl. Kunjachan Koottayma (Unit 25B)',
    nameMl: 'വാ. കുഞ്ഞച്ചൻ',
    patronSaint: 'Bl. Kunjachan',
    feastDate: 'October 16',
    location: 'ആനക്കയം (ഞൊണ്ടുവേലി)',
    zone: '7 - ജോർദ്ദാൻ',
    totalHouses: 8,
  },
  '26': {
    number: '26',
    nameEn: 'St. Teresa of Avila Koottayma',
    nameMl: 'വി. അമ്മ ത്രേസ്യ',
    patronSaint: 'St. Teresa of Avila',
    feastDate: 'October 15',
    location: 'P.N.P. റോഡ്',
    zone: '8 - ഓർത്തോണ',
    totalHouses: 14,
  },
  '27A': {
    number: '27A',
    nameEn: 'Mar Thoma Sleeha Koottayma (Unit 27A)',
    nameMl: 'മാർ തോമാശ്ലീഹ',
    patronSaint: 'St. Thomas the Apostle',
    feastDate: 'July 3',
    location: 'KV.M.S റോഡ്',
    zone: '8 - ഓർത്തോണ',
    totalHouses: 22,
  },
  '27B': {
    number: '27B',
    nameEn: 'St. Euphrasia Koottayma (Unit 27B)',
    nameMl: 'വി. എവുപ്രാസ്യ',
    patronSaint: 'St. Euphrasia',
    feastDate: 'August 29',
    location: 'KV.M.S റോഡ്',
    zone: '8 - ഓർത്തോണ',
    totalHouses: 18,
  },
  '28': {
    number: '28',
    nameEn: 'St. Joseph Koottayma (Unit 28)',
    nameMl: 'വി. യൗസേപ്പ്',
    patronSaint: 'St. Joseph',
    feastDate: 'March 19',
    location: 'KV.M.S റോഡ്',
    zone: '8 - ഓർത്തോണ',
    totalHouses: 13,
  },
  '29': {
    number: '29',
    nameEn: 'St. Paul Koottayma (Unit 29)',
    nameMl: 'വി. പോൾ',
    patronSaint: 'St. Paul the Apostle',
    feastDate: 'June 29',
    location: 'ടൗൺ ഹാൾ ഭാഗം',
    zone: '8 - ഓർത്തോണ',
    totalHouses: 10,
  },
  '30': {
    number: '30',
    nameEn: 'St. Pius X Koottayma',
    nameMl: 'വി. പത്താം പീയൂസ്',
    patronSaint: 'St. Pius X',
    feastDate: 'August 21',
    location: 'ചിറക്കടവ് ഭാഗം',
    zone: '9 - എഫ്രേം',
    totalHouses: 21,
  },
  '31': {
    number: '31',
    nameEn: 'St. Matthias Koottayma',
    nameMl: 'വി. മത്തിയാസ്',
    patronSaint: 'St. Matthias',
    feastDate: 'May 14',
    location: 'മഞ്ഞപ്പള്ളിക്കുന്ന്',
    zone: '9 - എഫ്രേം',
    totalHouses: 18,
  },
  '32': {
    number: '32',
    nameEn: 'St. Francis Xavier Koottayma',
    nameMl: 'വി. ഫ്രാൻസിസ് സേവ്യർ',
    patronSaint: 'St. Francis Xavier',
    feastDate: 'December 3',
    location: 'ടൗൺ ഭാഗം',
    zone: '9 - എഫ്രേം',
    totalHouses: 17,
  },
  '33': {
    number: '33',
    nameEn: 'St. George Koottayma (Unit 33)',
    nameMl: 'സെന്റ് ജോർജ്ജ്',
    patronSaint: 'St. George',
    feastDate: 'April 23',
    location: 'പഴയ ചന്തഭാഗം',
    zone: '9 - എഫ്രേം',
    totalHouses: 31,
  },
  '34': {
    number: '34',
    nameEn: 'St. Bernard Koottayma',
    nameMl: 'വി. ബർണാർഡ്',
    patronSaint: 'St. Bernard of Clairvaux',
    feastDate: 'August 20',
    location: 'മണിമലക്കുന്ന്',
    zone: '9 - എഫ്രേം',
    totalHouses: 17,
  },
  '35': {
    number: '35',
    nameEn: 'St. Matthew Koottayma',
    nameMl: 'വി. മത്തായി',
    patronSaint: 'St. Matthew the Apostle',
    feastDate: 'September 21',
    location: 'തോണപ്പാറ റോഡ്',
    zone: '10 - ഒപ്പീർ',
    totalHouses: 25,
  },
  '36': {
    number: '36',
    nameEn: 'St. Maria Goretti Koottayma',
    nameMl: 'വി. മരിയ ഗൊരേത്തി',
    patronSaint: 'St. Maria Goretti',
    feastDate: 'July 6',
    location: '20-ാം മൈൽ',
    zone: '10 - ഒപ്പീർ',
    totalHouses: 29,
  },
  '37': {
    number: '37',
    nameEn: 'St. Little Flower Koottayma (Unit 37)',
    nameMl: 'വി. കൊച്ചുത്രേസ്യ',
    patronSaint: 'St. Therese of Lisieux',
    feastDate: 'October 1',
    location: 'മൈലാംകാവ്',
    zone: '10 - ഒപ്പീർ',
    totalHouses: 23,
  },
  '38': {
    number: '38',
    nameEn: 'Immaculate Conception Koottayma',
    nameMl: 'അമലോദ്ഭവ മാതാവ്',
    patronSaint: 'Our Lady of Immaculate Conception',
    feastDate: 'December 8',
    location: 'ഇടത്തംപറമ്പ്',
    zone: '10 - ഒപ്പീർ',
    totalHouses: 23,
  },
  '39': {
    number: '39',
    nameEn: 'St. Alphonsa Koottayma (Unit 39)',
    nameMl: 'വി. അൽഫോൻസ',
    patronSaint: 'St. Alphonsa',
    feastDate: 'July 28',
    location: 'മണിമലക്കുന്ന്',
    zone: '11 - ബഞ്ചമിൻ',
    totalHouses: 21,
  },
  '40': {
    number: '40',
    nameEn: 'St. Margaret Mary Koottayma',
    nameMl: 'വി. മാർഗരറ്റ് മേരി',
    patronSaint: 'St. Margaret Mary Alacoque',
    feastDate: 'October 17',
    location: 'മണിമലക്കുന്ന്',
    zone: '11 - ബഞ്ചമിൻ',
    totalHouses: 13,
  },
  '41': {
    number: '41',
    nameEn: 'St. Mother Teresa Koottayma (Unit 41)',
    nameMl: 'വി. മദർ തെരേസ',
    patronSaint: 'St. Teresa of Calcutta',
    feastDate: 'September 5',
    location: 'മണിമലക്കുന്ന്',
    zone: '11 - ബഞ്ചമിൻ',
    totalHouses: 9,
  },
  '42': {
    number: '42',
    nameEn: 'St. Michael Koottayma',
    nameMl: 'വി. മിഖായേൽ',
    patronSaint: 'St. Michael the Archangel',
    feastDate: 'September 29',
    location: '20-ാം മൈൽ - പുന്നത്താനം',
    zone: '11 - ബഞ്ചമിൻ',
    totalHouses: 26,
  },
  '43': {
    number: '43',
    nameEn: 'Mother of God Koottayma',
    nameMl: 'ദൈവമാതാവ്',
    patronSaint: 'Mary Mother of God',
    feastDate: 'January 1',
    location: '20-ാം മൈൽ - പുന്നത്താനം',
    zone: '11 - ബഞ്ചമിൻ',
    totalHouses: 9,
  },
  '44': {
    number: '44',
    nameEn: 'St. Monica Koottayma',
    nameMl: 'വി. മോനിക്ക',
    patronSaint: 'St. Monica',
    feastDate: 'August 27',
    location: '20-ാം മൈൽ - പുന്നത്താനം',
    zone: '12 - എമ്മാവൂസ്',
    totalHouses: 17,
  },
  '45': {
    number: '45',
    nameEn: 'Our Lady of Lourdes Koottayma',
    nameMl: 'ലൂർദ്ദ് മാതാവ്',
    patronSaint: 'Our Lady of Lourdes',
    feastDate: 'February 11',
    location: 'ലീലാമഹലിന് സമീപം',
    zone: '12 - എമ്മാവൂസ്',
    totalHouses: 26,
  },
  '46': {
    number: '46',
    nameEn: 'St. Jude Koottayma (Unit 46)',
    nameMl: 'വി. യൂദാ',
    patronSaint: 'St. Jude Thaddaeus',
    feastDate: 'October 28',
    location: 'ആർ.ടി. ഓഫീസിന് സമീപം',
    zone: '12 - എമ്മാവൂസ്',
    totalHouses: 37,
  },
};
