import { UserRole } from '../models/Role';

export const rolesSeed = [
  {
    name: UserRole.SUPER_ADMIN,
    description: 'Full system control, user management, audit logs, configuration',
    permissions: ['*'],
  },
  {
    name: UserRole.ADMIN,
    description: 'Parish administration, families, parishioners, events, announcements',
    permissions: [
      'users.view',
      'families.view',
      'families.create',
      'families.update',
      'families.delete',
      'persons.view',
      'persons.create',
      'persons.update',
      'persons.delete',
      'koottayma.view',
      'koottayma.create',
      'koottayma.update',
      'koottayma.delete',
      'events.view',
      'events.create',
      'events.update',
      'events.delete',
      'announcements.view',
      'announcements.create',
      'announcements.update',
      'announcements.delete',
      'prayer_meetings.view',
      'prayer_meetings.create',
      'prayer_meetings.update',
      'prayer_meetings.delete',
      'mass.view',
      'mass.manage',
      'priests.view',
      'priests.manage',
      'organizations.view',
      'organizations.manage',
      'gallery.view',
      'gallery.create',
      'gallery.update',
      'gallery.delete',
      'readings.view',
      'readings.manage',
      'history.view',
      'history.manage',
      'settings.view',
      'settings.manage',
    ],
  },
  {
    name: UserRole.KOOTTAYMA_LEADER,
    description: 'Assigned Koottayma management, prayer meeting submissions, unit directory',
    permissions: [
      'families.view',
      'persons.view',
      'koottayma.view',
      'koottayma.manage_assigned',
      'prayer_meetings.view',
      'prayer_meetings.create',
      'prayer_meetings.update',
      'events.view',
      'announcements.view',
      'mass.view',
      'priests.view',
      'gallery.view',
      'readings.view',
      'history.view',
    ],
  },
  {
    name: UserRole.PARISHIONER,
    description: 'Standard parishioner mobile app and directory view access',
    permissions: [
      'families.view',
      'persons.view',
      'koottayma.view',
      'events.view',
      'announcements.view',
      'prayer_meetings.view',
      'mass.view',
      'priests.view',
      'gallery.view',
      'readings.view',
      'history.view',
    ],
  },
];

export const parishSeed = {
  name: "St. Mary's Forane Church",
  logoUrl: 'https://images.unsplash.com/photo-1548625361-195feeed7c5a?auto=format&fit=crop&w=300&q=80',
  patronSaint: 'Our Lady of Assumption (പരിശുദ്ധ മറിയം)',
  diocese: 'Archdiocese of Ernakulam-Angamaly',
  forane: 'Forane of St. Mary (Kadavanthra Forane)',
  address: 'Church Road, Kadavanthra, Kochi, Ernakulam, Kerala 682020',
  establishedYear: 1894,
  parishFeast: 'Feast of the Assumption of the Blessed Virgin Mary (August 15)',
  currentParishPriest: {
    name: 'Very Rev. Fr. Joseph Pulivelil',
    phone: '+91 94471 23456',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    serviceStartDate: new Date('2022-05-15'),
  },
  assistantPriests: [
    {
      name: 'Rev. Fr. Mathew Vadakkedath',
      phone: '+91 94472 34567',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      serviceStartDate: new Date('2024-05-10'),
    },
  ],
  totalFamiliesCount: 350,
  totalParishionersCount: 1420,
  totalKoottaymasCount: 4,
  institutions: [
    {
      name: "St. Mary's Higher Secondary School",
      type: 'School',
      description: 'Aided Higher Secondary School educating over 1,200 students since 1952.',
    },
    {
      name: 'Nirmala Bhavan Convent (CMC)',
      type: 'Convent',
      description: 'Convent of Congregation of Mother of Carmel rendering spiritual and social services.',
    },
    {
      name: 'Karuna Charitable Clinic & Day Care',
      type: 'Healthcare',
      description: 'Free healthcare and elderly daycare center run under Parish Social Action.',
    },
  ],
  officeInfo: {
    phone: '+91 484 2200112',
    email: 'office@stmarysforane.org',
    officeHours: 'Tue - Sun: 9:00 AM - 1:00 PM, 4:00 PM - 7:00 PM (Monday Closed)',
    address: 'Church Office, St. Mary Forane Road, Kadavanthra, Kochi 682020',
    mapLocation: {
      latitude: 9.9674,
      longitude: 76.2996,
      googleMapsUrl: 'https://maps.google.com/?q=9.9674,76.2996',
    },
    website: 'https://stmarysforane.org',
    socialMedia: {
      facebook: 'https://facebook.com/stmarysforanekadavanthra',
      youtube: 'https://youtube.com/@stmarysforanekadavanthra',
      instagram: 'https://instagram.com/stmarysforane',
      whatsapp: '+919447123456',
    },
  },
  welcomeMessage: {
    en: "Welcome to St. Mary's Forane Parish! A vibrant Catholic community dedicated to Christ through the maternal intercession of the Blessed Virgin Mary.",
    ml: 'വിശുദ്ധ മറിയത്തിന്റെ ഫൊറോന ദൈവാലയത്തിലേക്ക് ഏവർക്കും ഹൃദ്യമായ സ്വാഗതം! പ്രാർത്ഥനയിലും സ്നേഹത്തിലും ഐക്യപ്പെട്ട ക്രൈസ്തവ കൂട്ടായ്മ.',
  },
};

export const koottaymasSeed = [
  {
    name: 'St. Thomas Koottayma',
    number: 1,
    patronSaint: 'St. Thomas the Apostle',
    leader: 'Baby John Pulivelil',
    leaderPhone: '+91 98470 11001',
    assistantLeader: 'Rosily Mathew',
    assistantLeaderPhone: '+91 98470 11002',
    meetingLocation: 'Family residences (Rotating)',
    meetingDay: 'Sunday',
    meetingTime: '05:00 PM',
    description: 'Covering South Zone (Panampilly Nagar & Church Road sector)',
    status: 'Active',
  },
  {
    name: 'St. Joseph Koottayma',
    number: 2,
    patronSaint: 'St. Joseph the Worker',
    leader: 'Antony Puthussery',
    leaderPhone: '+91 98470 22001',
    assistantLeader: 'Gracy Thomas',
    assistantLeaderPhone: '+91 98470 22002',
    meetingLocation: 'Family residences (Rotating)',
    meetingDay: 'Sunday',
    meetingTime: '05:30 PM',
    description: 'Covering North Zone (Kadavanthra Junction & Subash Nagar)',
    status: 'Active',
  },
  {
    name: 'Holy Family Koottayma',
    number: 3,
    patronSaint: 'The Holy Family of Nazareth',
    leader: 'George Varghese Manjooran',
    leaderPhone: '+91 98470 33001',
    assistantLeader: 'Mary Devassy',
    assistantLeaderPhone: '+91 98470 33002',
    meetingLocation: 'Family residences (Rotating)',
    meetingDay: 'Saturday',
    meetingTime: '06:00 PM',
    description: 'Covering East Zone (Elamkulam & Canal Road sector)',
    status: 'Active',
  },
  {
    name: 'St. Alphonsa Koottayma',
    number: 4,
    patronSaint: 'St. Alphonsa of Bharananganam',
    leader: 'Dominic Thoppil',
    leaderPhone: '+91 98470 44001',
    assistantLeader: 'Annamma Cherian',
    assistantLeaderPhone: '+91 98470 44002',
    meetingLocation: 'Family residences (Rotating)',
    meetingDay: 'Sunday',
    meetingTime: '05:00 PM',
    description: 'Covering West Zone (Girinagar & Metro Station sector)',
    status: 'Active',
  },
];
